### ISSUE TITLE
useNativeDriver warning

### ISSUE THREAD

**Issue by dsuarezlogans** [pritishvaidya/react-native-password-strength-meter#12]
Hello,

I having a warning using this module, is about `useNativeDriver` I'm using react-native `0.62.2`.

Any suggestion how can I fix this? I added the property `useNativeDriver: false` in [here](https://github.com/pritishvaidya/react-native-password-strength-meter/blob/master/src/components/bar-password-strength-display.js#L45) and the warning disappear, but I don't know if that is the correct solution.

Thank you, this package is really helpful and easy to use keep the good work 👍 😄 

![image](https://i.imgur.com/StrcTnd.png)

**Comment by yg-yash** [comment]
I am also having this same issue

**Comment by ijshd7** [comment]
This might be a silly question, but I'm a noob and was wondering how I could make this change directly in my own project? I am already using this dependency and keep hitting that warning too, which is apparently halting the flow of the app

**Comment by mtwzim** [comment]
I am also having this same issue

**Comment by pritishvaidya** [comment]
It should be fixed now
