### ISSUE TITLE
Version inconsistency ?

### ISSUE THREAD

**Issue by NicoleEtLui** [pritishvaidya/react-native-password-strength-meter#3]
Hello,

first thanks for this awesome component !

I noticed something stranged but maybe i'm missing something ! Fresh installing your package we get the version `0.0.2` but there is only one release for `0.0.1`.

Moreover and that's more important, there is difference in the code on `github` and the code of the installed package.

I've only found one example:
[here](https://github.com/pritishvaidya/react-native-password-strength-meter/blob/master/src/components/box-password-strength-display.js#L63) the version installed says `label.label` instead of the correct `level.label`.

After fresh install:
![Capture d’écran 2019-06-26 à 12 33 28](https://user-images.githubusercontent.com/17101004/60173292-b1b67680-980e-11e9-87ad-81c4ef25d473.png)

Do you have an explanation ?

**Comment by pritishvaidya** [comment]
I haven't made any major changes to this package so there is no major release for now.
I have updated the new version with the changes in master branch.
