### ISSUE TITLE
Ref is not working 

### ISSUE THREAD

**Issue by ismailkhan89** [pritishvaidya/react-native-password-strength-meter#6]
- [ ] I have tried ref but its not working saying this3.Password.focus is not a function i am referring it from last textinput which is 
`<RNPasswordStrengthMeter 
                    ref = { ref => this.Password = ref }
                              // inputRef={(input) => { this.Password = input; }}
                              // inputRef={ref => { this.Password = ref; }}
          onChangeText={this.onChangePassword}
          passwordProps = {{
            variations: {
     digits: /\d/,
     lower: /[a-z]/,
    //  upper: /[A-Z]/,
     nonWords: /\W/,
   },
   scoreLimit: 60,
   minLength: 6,
   labelVisible: false,
            levels: [
  
     {
       label: 'Weak',
       labelColor: Colors.TITLE_FONT_COLOR,
       activeBarColor: '#ff6900',
     },
    {
       label: 'Fair',
       labelColor: Colors.TITLE_FONT_COLOR,
       activeBarColor: '#f2cf1f',
     },
     {
       label: 'Strong',
       labelColor: Colors.TITLE_FONT_COLOR,
       activeBarColor: '#14eb6e',
     }
      ],
  } }
          
          containerWrapperStyle= {{backgroundColor:'#fff', textAlign:'center',
          borderWidth: 1,
    //  borderColor: Colors.BORDER_GRAY,
     borderColor:'#dd9aad',
     backgroundColor:'#fff',
    width: Sizes.WINDOW_WIDTH * 0.9,
    height: 40,
    marginLeft:-1,
    justifyContent: 'center',
    marginBottom: 10,
    borderRadius: 40}}
          inputWrapperStyle={[ {backgroundColor:'transparent',  height:50, textAlign:'center'}]}
          inputStyle={{height:65, textAlign:'center', }}
          placeholderStyle={{textAlign:'center'}}

          maxLength={15}
          autoCapitalize="none"
          underlineColorAndroid="transparent"
          returnKeyType={'next'}
          secureTextEntry
          placeholder="Password"
          autoCorrect={false}
          value={this.state.password}
          imageWrapperStyle ={{ alignSelf: 'flex-end', marginRight: -6 }}
          // onChangeText={value => this.setState({ password: value, passwordErrorFlag: false })}
          
          
          
          meterType="text"
          
          
        />`

**Comment by ganmor** [comment]
Here is an example ( I think this can be closed)

`<RNPasswordStrengthMeter
						onChangeText={this.updatePassword}
						meterType="bar"
						inputProps={{
							onKeyPress: this.onEnterValidate,
							returnKeyType: 'send',
							secureTextEntry: true,
							ref: (ref) => (this.ref = ref),
							autoCorrect: false,
							label: i18n.t('global-user:login.passwordChoosePlaceholder'),
							testID: 'login.default.create.password.input',
							accessibilityLabel: 'login.default.create.password.input',
						}}
					/>`
